### ISSUE TITLE
Version 5.5.* support

### ISSUE THREAD

**Issue by Bakudan** [kevindierkx/laravel-domain-localization#1]
Hi Kevin ! I'm really fascinated about the idea of using your awesome repository but please can you update the "illuminate/support" to add the last 5.5.* version ? :)

**Comment by kevindierkx** [comment]
@Bakudan Sure thing!

**Comment by kevindierkx** [comment]
@Bakudan Hey, I've removed the rather strict version constraints and tested it in a clean L5.5 installation. Everything should be good to go! ;)
