### ISSUE TITLE
Add support for 'default' locale when TLD is not found in config

### ISSUE THREAD

**Issue by MelvinSnijders** [kevindierkx/laravel-domain-localization#13]
If the current TLD is not found in the configuration file, a default locale could be used.
This would be useful for development.

**Comment by MelvinSnijders** [comment]
When testing locally, an exception is thrown:
![image](https://user-images.githubusercontent.com/25155102/110619116-b617f400-8197-11eb-9622-d5e6152bfee8.png)
It'd be nice to configure a default locale to use (or use the app locale) when the TLD is not found in the config.

**Comment by kevindierkx** [comment]
This might be related to #19, I'll take a look when I have some spare time!
