### ISSUE TITLE
Multiple languages per domain

### ISSUE THREAD

**Issue by Nizari** [kevindierkx/laravel-domain-localization#2]
At the core this package looks great, thank you!
However, is it also possible with this package to have multiple languages *per* domain.

For example: 
1) example.be => example.be/en , example.be/nl, example.be/fr (en-BE, nl-BE, fr-BE)
2) example.nl => example.nl/en , example.be/nl (en-NL, nl-NL)

**Comment by kevindierkx** [comment]
Nope, at the moment only one locale per TLD is supported. It would be possible to add though.

**Comment by tmihetec** [comment]
Any progres on this topic? Maybe some hint how to do this? i have 4 domains with different TLD, but also 2 domains on same TLD (.com) for which i would like to be able to set different language...

**Comment by kevindierkx** [comment]
Looking at the changes made to https://github.com/mcamara/laravel-localization I would recommend using that instead. I don't think it would have any added benefit to also add similar logic to this package.

You can of course use both this package and 'laravel-localization' side by side, just keep in mind not to use the middlewares of both packages.

I might take another look at this if this still is a problem.
