### ISSUE TITLE
Is this still working in ^5.6?

### ISSUE THREAD

**Issue by Roboonl** [kevindierkx/laravel-domain-localization#3]
Hi Kevin,

I'm trying to get this package to work in Laravel 5.6 but it seems like the locale is not changing.

When I debug the `setCurrentLocale` method in your package, I can see package is trying to change the locale to 'en', but when I use the helper method `Localization::getCurrentLocale()` it returns the default locale.

The same thing happens when I try to retrieve the locale in a controller using `\Localization::getCurrentLocale()`, it returns the default locale.

When I retrieve the locale after setting it with `\Localization::setCurrentLocale('en')` the locale is actually changed. (For example in a controller)

Do you have any ideas?

**Comment by kevindierkx** [comment]
Sorry for the very late reaction. I've recently updated the package to support L6.x, there I didn't see any issues with setting the locale.

Please note when using the middleware the locale will be set to the matching locale from the requests URL. So for `example.com/page` the locale would be set to `en` by default. Setting the locale manually would only change it for that specific request.

Could you, if you're even using the package anymore test it with the latest release. Until then I'll close this issue.
