### ISSUE TITLE
Support for Laravel 6

### ISSUE THREAD

**Issue by voicecode-bv** [kevindierkx/laravel-domain-localization#4]
Hi @kevindierkx, 

Can you please update the version constraints to support Laravel 6? 

Thanks!

**Comment by voicecode-bv** [comment]
@kevindierkx can you please update the version constraints? Would really help a lot. Thanks!

**Comment by kevindierkx** [comment]
I might have some time later this week, feel free to open a PR if you want to ;)

**Comment by voicecode-bv** [comment]
@kevindierkx thanks! PR is submitted.

**Comment by kevindierkx** [comment]
Relates to #5

**Comment by kevindierkx** [comment]
The 3.0 release has been tagged and tested, should work without problems on L6.x.

Please note: Some small BC changes were introduced in the TLD methods. These now require a URL instead of resolving the URL directly from the request instance.
